"""Schema refactoring

Revision ID: 75f96f48f35b
Revises: 9df15f008759
Create Date: 2023-03-19 17:22:40.866332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f96f48f35b'
down_revision = '9df15f008759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
